- id: '1573298066914'
  alias: Turn on fan and light when back home at evening
  description: Fires during 7-9pm on coming home only
  trigger:
  - entity_id: person.ping_seng
    from: not_home
    platform: state
    to: home
  condition:
  - after: '19:00:00'
    before: '20:00:00'
    condition: time
  - condition: and
    conditions:
    - condition: state
      entity_id: person.li_ping
      state: not_home
  action:
  - service: script.living_fan_3
  - data: {}
    entity_id: switch.living_light_power
    service: switch.turn_on
  mode: single
- id: '1573951043840'
  alias: Ring Doorbell Pressed
  description: ''
  trigger:
  - entity_id: binary_sensor.front_door_ding_2
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      media_content_id: https://www.soundjay.com/door/doorbell-1.mp3
      media_content_type: audio/mp3
    entity_id: media_player.botanique_home_mini
    service: media_player.play_media
- id: '1576134652401'
  alias: Notify when front door opened
  description: ''
  trigger:
  - entity_id: binary_sensor.0x00158d00039ab792_contact
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.ping_seng
    state: not_home
  action:
  - data:
      message: front door is opened
      title: door open
    service: notify.mobile_app_hd1900
- id: '1576895034778'
  alias: Turn on kitchen light if motion detected
  description: Only after sunset
  trigger:
  - device_id: 9536fc4188c84f629537a5e8408cf3b0
    domain: binary_sensor
    entity_id: binary_sensor.0x00158d0003a4e7ed_occupancy
    platform: device
    type: motion
  condition:
  - condition: or
    conditions:
    - after: sunset
      after_offset: -01:00:00
      condition: sun
    - before: sunrise
      before_offset: +01:00:00
      condition: sun
  action:
  - device_id: e67f3b3a8afe48fbb15a2f283cf2522a
    domain: switch
    entity_id: switch.kitchenlight_switch
    type: turn_on
  mode: single
- id: '1576895089498'
  alias: turn off kitchen light if no motion
  description: ''
  trigger:
  - device_id: 9536fc4188c84f629537a5e8408cf3b0
    domain: binary_sensor
    entity_id: binary_sensor.0x00158d0003a4e7ed_occupancy
    for:
      hours: 0
      minutes: 0
      seconds: 30
    platform: device
    type: no_motion
  condition: []
  action:
  - device_id: e67f3b3a8afe48fbb15a2f283cf2522a
    domain: switch
    entity_id: switch.kitchenlight_switch
    type: turn_off
  mode: restart
- id: '1576984737131'
  alias: Turn off master aircon if temp < 2x degrees
  description: ''
  trigger:
  - below: 27
    device_id: 55287d9dac5f4f6882391ee7eaa3a2c8
    domain: sensor
    entity_id: sensor.0x00158d0003d45b43_temperature
    for:
      hours: 0
      minutes: 10
      seconds: 0
    platform: device
    type: temperature
  condition:
  - after: 03:00:00
    before: 06:00:00
    condition: time
  action:
  - data: {}
    entity_id: switch.master_aircon_cool_27
    service: script.master_aircon_off
  - service: script.master_fan_1
  mode: single
- id: '1578872764913'
  alias: turn off master aircon completely on weekdays
  description: ''
  trigger:
  - at: 06:30:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - entity_id: switch.master_aircon_vent
    service: script.master_aircon_vent
  - delay: '600'
  - entity_id: switch.master_aircon_vent
    service: script.master_aircon_off
  - data: {}
    service: script.master_fan_1
- id: '1590156374296'
  alias: Turn off fan at night if temp drops
  description: ''
  trigger:
  - above: '0'
    below: '29'
    entity_id: sensor.0x00158d0003d45b43_temperature
    platform: numeric_state
  condition: []
  action:
  - data: {}
    service: script.master_fan_off
- id: '1597928164543'
  alias: Turn on living room LED on motion
  description: ''
  trigger:
  - device_id: 41ac1ecc2b9240da8f4de7012743c8c1
    domain: binary_sensor
    entity_id: binary_sensor.0x00158d000522afb5_occupancy
    platform: device
    type: motion
  condition:
  - below: 10
    condition: device
    device_id: 41ac1ecc2b9240da8f4de7012743c8c1
    domain: sensor
    entity_id: sensor.0x00158d000522afb5_illuminance
    type: is_illuminance
  action:
  - data: {}
    entity_id: switch.tv_console_led
    service: switch.turn_on
  mode: single
- id: '1597928295788'
  alias: Turn off living room LED if no motion
  description: ''
  trigger:
  - device_id: 41ac1ecc2b9240da8f4de7012743c8c1
    domain: binary_sensor
    entity_id: binary_sensor.0x00158d000522afb5_occupancy
    for:
      hours: 0
      minutes: 0
      seconds: 30
    platform: device
    type: no_motion
  condition: []
  action:
  - data: {}
    entity_id: switch.tv_console_led
    service: switch.turn_off
  mode: restart
