
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include themes.yaml
  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Living room TV
media_player:
  - platform: webostv
    host: 192.168.101.140
    name: Living Room TV
    filename: webostv.conf
    timeout: 5
    turn_on_action:
      service: switch.turn_on
      entity_id: switch.lg
    customize:
      sources:
        - livetv
        - youtube
        - Amazon Prime Video
        - Emby
        - netflix
        - chromecast
        - desktop

switch:
  - platform: wake_on_lan
    name: lg
    mac: "A8:23:FE:6D:12:04"

# Master bedroom broadlink switch
  - platform: broadlink
    host: 192.168.101.230
    mac: 'c8:f7:42:83:83:6d'
    timeout: 15
    retry: 5
    switches:
      master_aircon_cool_25:
        friendly_name: "Master Aircon Cool 25"
        command_on: 'JgBMAms6DykNLA4ODRANDw0sEAwNEA4qECkQDA8qDg4PDg4qDisODg8qDioPDg0PDyoODg0QDioODw4ODRAODg0QDQ8NEA0PDRANDw8ODg4ODg4PDQ8PDg0PDw4RCw4PDSsODw4ODw4NDw0QDSsNLA4ODw4ODg8qDg4NEA0rDg8NDw8ODQ8NEA0rECkQDA8qDSwNDw0QDg4PDg4ODg4PDg0PDyoODg0sDRAOKg4PDSsOKw0rDRAODg0QDg4PDg0PDg8ODg8ODg4NEA4ODw0ODw4ODRAODg4PDg4ODg0QDg4ODw0PDw4NDw0QDg4NEA0PDg4PDg4ODw4ODg4ODg8NDw8ODQ8PDg0PDRANDw8ODQ8PDg4ODQ8PKg4ODw4ODg4ODg8NKw8ODQACMHU5DisNLA0PDRANDw0rDg8ODw0rECkNDw0sDQ8PDg0rDSwODg8qECgPDg4ODyoNDw4PDSwNDw0QDg4NDw8ODg4NEA4ODg4ODw4ODRAODg0QDQ8PDg4ODQ8PDg4ODyoODg8ODg4ODg8ODioOKw4ODQ8PDg4qEA0ODg4rDw0ODg8ODg4PDg4qDyoODw0rECkNDw0QDg4NEA4ODRANDw0QDSsQDQ4qDg8OKg0QDSsNLA4qEA0NDw8ODg4NEA0PDw4NDw0QDg4NEA0PDg4PDg4ODw4ODg0PDg8ODg4PDg4NEA0PDRANDw0QDQ8PDg4ODg8NDw0PDw4NDw8ODw4NDw0PDw4ODg8ODQ8PDg4ODRAODg0PDw4OKg0QDg4NEA4ODw4OKg0QDQANBQAAAAAAAAAAAAAAAA=='
        command_off: 'JgBOAm45DisOKg4PDg4NEA4qDg8ODg8qDioPDg0rDg8NDw4rDSwODg0sDSsPDg8ODioODw4ODisODwwQDQ8ODg8ODg4NEA4ODw4ODg4OEQwNDw8ODQ8NEA0PDw4QDA4ODw4PDg0PDRAODg8ODioOKw4ODw4ODg0sDg4PDg4qDg8ODg0QDQ8PDg4rDSsODg4rDioODw4ODg8ODg0QDg4PDg0PDisNDw8ODisNKw4ODyoOKw4qDg8PDQ0QDg4PDg0PDRAPDQ8ODg4PDg4ODg4ODw4ODw4ODg4ODw4QDA8ODg4NEA0PDg8NDw4ODw4NDw4PDg4PDg4ODw4ODg4OEQwNDw8ODQ8PDg0PDRANDw8ODQ8PDQ8ODQ8PDg4qDw4QDA0QDioODw4ODoAIAAGndTkOKw4rDg4PDg4ODSwNDw4PDSsOKw4ODisODw0PDioPKg4PDioOKw4ODRANKw4PDg8OKg4PDg4NEA0PEAwODw4ODg8ODg8OEAwNEA4ODg8ODg0PDw4ODg0QDQ8ODw4ODw4ODg8ODg4PKg0sDQ8ODg0QECgODxAMDSwODg8ODg8NDw8ODioOKw4ODSwOKg4PDg4PDg0PDw4NDw0QDQ8PKg8NDw4NKw4rDg4PKg4qDisODw0PDg4PDg4ODg8ODw4ODQ8PDg4ODg8NDw0QEAwODw4ODRAODg0QDg4NEA4OEAwPDg4ODw4ODg8ODQ8PDg0PDg8NDw0QDQ8ODg4PEAwPDg0PDw0PDg4ODw4NDw8ODQ8NEA4OECkNDxAMDw4NLA0PDg4NAA0FAAAAAAAAAAAAAA=='
      master_aircon_cool_26:
        friendly_name: "Master Aircon Cool 26"
        command_on: 'JgBMAms4ECkOKw4OEA0PDQ0sDQ8NDw4rDioSCw0sDQ8QDQ0rDisODg0sDSsODw0PDSwODg0QDSsODw0PDg8NEA0PDRANDxANEAwPDQ4PDw0QDQ0PEA0PDRANDw0QDQ0PDSwNDw0QDQ8NEBAMDSsOKw4ODRAPDRANDSsNEA8pDg8QDA0QDQ8NEA0rDisNDw0sDSsNEA0PECkODg0QEAwNEA8NDSwNDw0QDw0NDw0QDSsQKQ4OEA0NDw0QDw0NEA0PDRANDw0QDw0RDA8NDQ8ODw8NEA0QDA0QDw0NEA8ODQ8QDQ8NDw0NEBAMDRAPDQ0QDw0NDxANDQ8ODw0PEQwNDxANDw0NEA8NDw0QDQ8NDRANDw0PDg8PDRApDisPKQ4rDioOKxAoDgACMHU5DSwNKxEMDQ8QDQ0rDw4QDBApDioODw0sDQ8QDA4rDisNDw0rDisODw8NECkODg0QDSsRDA0PEA0NDxEMDQ8NDw0QDQ8NEA8NEQwPDQ0QDQ8QDQ0PDRANDxEMDykODw8NDRANDxEMDykOKw4OEA0NDw8NECkNDw0sDQ8ODxAMEA0NDw0sDyoNDxAoDisNEA0PECkODg4PDQ8QDQ0QDykNEA0PEA0PDQ8ODSsOKw4OEA0NDw0QDQ8QDQ8NDQ8QDQ8NDRANDxAMDg8NDxEMEAwNEBAMEA0PDQ0QDQ8PDRANDw0NEA8NDRAPDg0PEA0PDQ8NDRAQDA0QDw0NEA8NDQ8QDQ0PDRANDxANDQ8QDQ8NDRAPDQ8pDisOKg0sDisOKg0sDgANBQAAAAAAAAAAAAAAAA=='
        command_off: 'JgBMAmo5DisOKhANEAwNEA0rDg8QDBApDioODw0sDg4RDA0rDisODhApECkPDRANDykODw8NDyoNDxANDQ8QDBEMDQ8ODw8NEA0PDRANEAwPDg8NDw0QDQ0PEA0NDxANDRAPDQ0PEQwPDRANDSsOKw4ODRAQDBANDSsODw0sDQ8QDQ0PDw0ODw0sDioODxAoDisODhANDykODw8NEAwQDQ0PECkODg0QDw0QDQ8NECkNKw4PDw0RDA0PDg8QDQ0PEA0PDQ8NEA0PDRANDw0NEA8NDRAPDQ0QDQ8NEA8NDRAPDQ8NDRAPDQ8NEA0PDQ0QDw0NEA0PEA0PDQ8NEA0PDRANDw0QDQ8NDRAPDQ0QDw0PDRANEAwQDBApDisOKg4rDg4QKQ4qDgACMHQ6DioOKw4ODg8PDRApEA0NDw8pDisODw0rDg8PDRApDioODw0rDisODw8NDyoNDw8ODykODw8NDRANDw8NDRAPDQ0QDw0RDA8NDRAPDQ8ODw0NDxEMDw0NEA0PDg8PDRANDw0QDQ8NDyoOKg8ODw0NEA0PESgPDQ0sDg8QDA0QDQ8RDA0rDisODg0sDisNDw0QDykNEBAMDRAPDQ8ODykODhANEA0ODhANDykOKw0PEA0PDQ4PDw0QDBANDw0QDQ8NDw0ODw8NDRAPDRANDQ8NEA8NDRAPDRANDQ8QDQ0PEQwPDQ8NEA0NEA8NDw0QDQ8NDRANDxEMDQ8QDQ8NEA0NEA8NDw0QDQ8NEA0PDQ8ODw0PDQ0sDSwQKA4rDg4PKhApDgANBQAAAAAAAAAAAAAAAA=='
      master_aircon_vent:
        friendly_name: "Master Aircon Vent"
        command_on: 'JgBMAmo6DisQKBELEA0NDw4rDRAQDBApDSsODw0rDg4ODw0sDioODw0rDisODw8NECkODhEMDykODw8NEA0NDxANEAwQDQ8NDQ8NEA0PEA0PDRANEAwNEA8NDw0NEBAMECkNDxANDQ8QDQ0PECkOKw0rDg8PDQ0QDw0NEA8pDRAPDRANDw0RCw4PDQ8ODw0sDioODw0PEA0PDRANDQ8NEA8NDykODw8pDg8NKw4rDisNKw4PDw0QDQ0PEAwQDQ0PEA0PDRANDw0QDBANDw0NEA0PEA0PDQ8ODw0PDRANDw0QDBANEA0PDRANDw0QDQ0PDQ8ODxANDw0NEA8NDRAPDRAMEA0PDRANDw0PDRANDw0ODxAMDRAQDA8qDg8NDxEMDykODw8NEAACLnc3DioNLA0PDg8PDRApDQ8QDQ0rDSwODw8pDg8NEA8pDisODhApDisODg0QDykODw8NECkODg4PDw0RDA0PEA0PDRANDw0PDRANDQ8RDA8NDRAPDRAMEA0NDw0QDykODw0PDg8QDQ8NECgPKg4qDg8QDQ8NEAwQDQ0sDg4QDQ8NDQ8QDQ8NEA0PDRApDioOEA8MEAwODxAMDg8PDRANDykNEBAoDg8NKw4rDioOKw4OEQwPDREMDw0NDxANDw0NEA0PEA0NDxANDw0QDQ8NEQwNDxANDQ8QDQ8NDRAPDQ8NEA0PDRAMEA0PDQ0QDQ8QDQ8NEA0PDRANEAwPDRANDw0QDQ8NEA0QDBANDQ8NEA0PEA0PDQ0sDg4ODw0PDisODw8NDQANBQAAAAAAAAAAAAAAAA=='
        command_off: 'JgBMAms5DisOKg4PEAwNEA8pDRAPDRApDSsQDQ0rDg8NDw0sDSsODw0sDSsODw8NECkPDRANDykNEA0PDRAPDRANDw0NEA8NEA0QDA8NEA0NDxANDQ8NDw4PDw0QDQ8NDw4PDQ0QDRAPDRANDykOKw0rDg8PDQ0QDw0NEA8pDg8PDQ0QDQ8QDQ8NDw0QDQ8pDisODhANDQ8QDQ8NDRANDw0QDykODw8pDw4NKw4rDisNKw4PDw0NEA8NEA0PDRANDw0PDRANDw0NEA0PDRAPDRANDw0PDQ0QDw0QDQ0PDw4PDQ0QDw0QDA4PDw0ODw8NEA0NDxANDw0NEA8NDw0QDQ0QDw0NDxANDw0QDQ0PDRANDxANDw0PDg8pDg8PDQ0QDQ8PDRANDQACMHU5DisOKw4OEA0NDxApDQ8QDQ8pDisPDg8pDg8PDQ8qDioODw8pDisODg0QDykODw0PECkODhANDQ8QDQ8NDRANDxANDQ8QDQ8NDw0QDQ8NDRAPDQ0QDw0PDg0PDRAPDRANDw0QDQ8NDykOKw4rDg4PDRANDw0QDQ8pDg8NDw8ODw0QDQ0PEA0PDQ8pDisODw4OEAwODw8NEA0PDRANDykODw8pDg8NKw4rDioOKw0PEA0PDQ8NEA0PDRANDw0PDg8NDw0NEBAMDRAPDRANDw0QDBANDw0QDQ8NEA0NDxANDQ8PDRANDg8PDRANDQ8PDg8NEA0PDRAMDw4NDxANDw0NEA8NEAwQDQ0QDQ8PDRANDw0NEA8pDg8ODg8ODw0QDQ0PEAANBQAAAAAAAAAAAAAAAA=='
      master_aircon_feel:
        friendly_name: "Master Aircon Feelmode"
        command_on: 'JgBMAmw3DisOKw4ODw4ODg0sDg4ODg4rDisODg0sDg4ODw0rDisPDg0sDSsODw4ODisODg4PDSsNEA0PDw4ODg4ODg8NDw8ODQ8NEA4PDg4ODg8ODg4NEA4ODg4NEA4ODyoODg8ODQ8NEA0PDw4ODg0PDw4ODg0QDQ8PDQ4rDg8ODg4ODRAODg8qDioODw4qDisNDw8ODSsNEA0PDw4NDw0PDyoODw4ODSwOKg4PDSsOKw0rDw4NDw4PDg4PDg4ODw4NDw4PDQ8NEA4ODRENDg4ODw4ODg4ODg8NDw8ODg4NEA4ODRANDw8ODg8NDw4ODg8ODw4ODQ8ODw4ODRANDw4PDg4NDw8ODg4PDg0PDRAODg8ODg4NEA4qDg4PKg4PDSsODw4ODQACMXQ5DisNLA0PDw4NEA4qDg4PDg4qDyoODw0rDg8NDw0sDSsODw0sDioODw4ODSwNDw8ODioPDg4ODw4NDw0QDQ8NEA4ODg4PDg4ODw4ODg0QDg4NDw4PDg4ODw4ODyoNDw4PDg4PDg4ODQ8ODw0PDRAODg0QDg4PDg4qDg8NDw4PDg4PDg4rDSsODw0rDSwODg4PDSsPDg0QDg4NEA4ODyoODg8NDyoOKw4ODSwOKg8qDQ8ODw4ODRANDw0QDg4NEA0PDg4NEA0PDRANDw4PDRANDw4ODw4ODg0QDg4PDg0PDw4ODg8ODg4ODw0PDRANDw8ODg4NEA4ODRAODg4ODw4ODg8ODQ8NEA4ODg8NDw8ODQ8NDw8qDg8NKw4PDSwODg0QDQANBQAAAAAAAAAAAAAAAA=='
        command_off: 'JgBMAmo6DioNLA0PDw4ODg0sDg4PDg0rDisODw0rDg8ODg0sDioODw0sDioNEA4ODSwNDw0QDicRDg8ODQ8ODw4ODRAODg0QDQ8NEA4ODRAODg4ODg8ODg8ODQ8ODw0PDg4NEA0PDw4ODg0QDg4PDQ8ODg4ODw0PDRAODg0sDw0PDg0PDg8ODw4qDSwODg8qDioNEA0PDSwODg8ODg4NEA4ODioPDg4ODisOKw4ODisOKg4rDg8NDw0QDQ8NEA4ODg8ODg0QDg4PDg4PDQ8ODw0PDg8ODg4ODw4ODg8ODQ8NEA0PDRAODg4ODw4NDw0QDg4PDg4ODRAODg0QDQ8ODw4ODw4ODg4PDg4ODg4PDQ8PDg0PDw4NDw0sDQ8OKw4PDQ8PDg4ODQACMXQ5DyoNLA0PDRAODw0rDRAODg0sDisODg0sDg4PDg0rDisODg8qDSsPDg8ODSsODw0PDyoODg0QDg4PDg4ODg8ODg4ODg8NDw4PDg4NEA4ODRAODg0QDQ8NEA4ODw4ODg4ODg8ODg8ODQ8NEA4ODRANDw8ODQ8NEA4qDRANDw0PDg8ODg8qDioODw4qDisODg8ODSsODw4ODRAPDg0PDSwODg8ODSsPKg4ODisOKhApDRANDw0QDg4PDg4ODw4ODg0QDQ8ODw4ODw4NDw8ODg4ODg4PDg4PDg0PDRANEA4ODQ8ODw4ODw4ODg0QDQ8PDg4ODg4PDg0PDw4ODg4ODw4NEA4ODRAODg0PDg8NDw4PDg8NDw0sDg4NLA4ODRAODg0QDQANBQAAAAAAAAAAAAAAAA=='

# Living room broadlink switch
  - platform: broadlink
    host: 192.168.101.56
    mac: '78:0f:77:63:75:f3'
    type: rm2_pro_plus
    timeout: 15
    retry: 5
    switches:
      # Living room light
      living_light_power:
        friendly_name: "Living Light"
        command_on: 'sgBKAQodCx0KHgodCh4LHQoeCh0LHQodCx0KHgodCx0LHR0KHgoLHQoeCh0eCgodHgoeCgsdHQoeCgoeCh0LHQodC5MKHQsdCxwLHQsdCh0LHQoeCh4KHQsdCh0LHQsdCh4KHR4KHgoKHQsdCh4dCgoeHQsdCwodHgodCwodCxwLHQsdCpMKHgodCx0KHQsdCx0KHgodCx0KHgodCx0KHgodCx0KHh4JHgoKHQsdCx0eCQsdHgoeCgodHgoeCgoeCh0LHQoeCpILHQsdCh0LHQoeCh0LHQoeCh0LHQsdCh0LHQodCx0LHR4KHgkLHQsdCh4dCgsdHgodCgsdHgodCgsdCh4KHQsdCpMKHgodCx0KHQsdCh4KHQsdCx0KHQsdCx0KHQsdCh4KHh0KHgoKHgodCx0eCQsdHgoeCgoeHQoeCgodCx0KHgodCwAF3AAAAAAAAAAAAAAAAAAA'
        command_off: 'sgBKAQodCx0LHQoeCh0KHh0LCh0KHgoeCh0LHQodCx0eCh4KHQsKHQsdCh0eCgoeHQsdCgsdHgodCgoeCx0KHQsdCpMKHQoeCh0LHQodCx0LHR4KCh4KHQoeCh0LHQoeCh0eCh4KHQsKHQsdCh4dCgsdHQseCgodHgodCgsdCx0KHgodC5IKHgodCh4KHQsdCh4KHh0KCx0KHgodCx0KHQsdCh4eCh0KHgoKHgodCx0dCwodHgoeCgodHgoeCgodCx0LHQoeCpIKHgodCx0LHAsdCx0KHh4JCx0KHgodCx0LHQoeCh0eCh4KHgkLHQoeCh0eCgodHgoeCgsdHQoeCgoeCh0LHQoeCpMKHgoeCh0LHQodCx0KHh4KCh4KHQoeCh0LHQodCx0eCh4KHgkLHQoeCh0eCgsdHQseCQsdHgodCgoeCh0LHQoeCgAF3AAAAAAAAAAAAAAAAAAA'

      # Living room aircon
      living_aircon_cool_25:
        friendly_name: "Living Aircon Cool"
        command_on: 'JgBMAnA6DioOKw8OEQsODw0sDQ8RDA0sDSwODhEoDg8NEBEnDyoODxEnDisPDhELDisODw0PDisNEBEMDQ8RCxEMEQsRDBEMEAwRCxEMEQsODxELDg8RCxILEQwNDw4PDSwODg4PEQsRDBELESgRKA4PEQsODw0sDQ8ODxEoDQ8RDA0QDQ8RDA0rDyoPDg0rDisPDg0QEAwRDA0QEAwODxELESgODxAoDw4OKw0sDisNKw4rDw4RCxEMEQsRDA4PDQ8ODxELEgsODxELDg8RCxEMEQsRDBAMEQwRCxEMEQsODxEMDQ8RDA8ODg4RDBAMDg8RDBELEQwQDBEMEQsODxELEA0NEBAMEQwQDA0QDQ8RDBELEQwNLA0PDg8NLA4ODg8RJw8ODQACMnU6DSwNKw8OEQwNEBAoDg8QDBEoDisODhEoDRAQDBEoDSwODhEoDisNDxEMESgODhEMDSwODxAMDRAQDBAMEQwRCxEMEAwQDRANEAwODxAMDg8QDBANDw4RCxEMDisODxELEQwQDBEMECkQKA8OEQsRDBApDQ8QDQ0sDg4ODxELDg8RCxApDyoODw0rEycQDA4PEQsQDRELEQwQDQ0PESgODg4sDQ8RKA4rDioPKg8qEQsODxANEQsODxELEQwQDA4PEAwQDQ8OEA0QDA4PEAwQDRELEQwRCxEMDRAPDRANDQ8QDRELEA0NDw4PEQsQDRAMDg8QDQ0PEQwODxAMEA0QDBANEAwRDBAMDg8RCw4PEA0NLA0PEQ0MLA4OEQwQKRAMEQANBQAAAAAAAAAAAAAAAA=='
        command_off: 'JgBMAnI4DisNLA4OEA0QDA4rDw4QDA4rDisODw0rDw4QDBApDisQDRApDisQDBANECgPDhANDykPDg0QDw0QDBANEA0NDxANDQ8ODw0QEAwPDg8NEA0NDxANEAwODxAMDw4NEA8NEA0NDxANECkRKA0PEA0QDA8qDw4QDBApDg8PDQ8NDg8ODw0rECkODxApDisODg4PEAwPDg4PDQ8ODw0QDykODxApDQ8QKQ4rECgOKw8qDg4QDQ0QDw0ODw4OEA0QDBANEAwQDQ8NEA0ODg4PEAwODxANDw4ODg8OEAwODw8ODw0QDQ8NEAwQDQ0QDw0QDQ0PEA0PDRANDQ8ODw8ODw0PDQ4PEA0NEA4ODg8QDBANDg4PKhAMEA0PKhAMDisODw8NDgACNnU6DisPKQ8ODw0ODw8qDg4QDRApDioODw0sDQ8ODw4rDisODhApDyoODg4PECkODg4PDyoODhANDQ8QDRAMDg8ODw8NDg8PDRANDw0PDg8NDg8PDg0PDw4PDg0PDg8PDRANEAwPDhAMDyoOKw4ODg8PDg8pDw4PDRApDg8PDQ8ODg4QDBApDisNEBAoDisPDhAMEA0QDBANDw4NDxANDyoODg8qDw0PKg8qDisOKw4rDg4ODw4OEA0PDRAMEA0NEA0PDw4PDQ8ODw0PDg8NEA0PDRANDRAODg4PDw0QDQ8NEA0QDBANDw0PDg8NDg8QDA4PDw4PDQ8ODw4QDA4PDw0QDRANDw0QDA8ODRAPDRANDQ8QKQ8ODQ8OKw8ODSsPDg8NEAANBQAAAAAAAAAAAAAAAA=='

      # Master room light
      master_light:
        friendly_name: "Master Light"
        command_on: 'sgBKAQodCh0LHQodCx0KHQoeCh0KHQsdCh4KHQoeCh0KHR4KCh0eCh4JHgodCh4KCh0KHgodCh4KHQoeHQoKHQsdCpIKHQsdCh0LHQodCx0KHQsdCh0LHQodCx0KHQoeCh0KHR4KCh0eCh4JHgoeCR4KCh0LHQodCx0KHQsdHQoLHAsdCpILHQodCx0KHQoeCh0LHQodCh0LHQodCx0KHQsdCh0KHh0KCh4dCh4KHQoeCh0KCh4KHQsdCh0KHQsdHgkLHQodCpMKHQodCx0LHAsdCh0LHQodCx0KHQsdCh0KHgodCxwLHR4KCh0dCx0KHQsdCh0KCx0KHQsdCxwKHgodHgoKHQodC5IKHQodCx0LHAsdCh0LHQoeCh0KHQscCx0KHgodCh0LHR4JCx0dCh4KHgkeCh4JCx0KHQsdCh0LHQodHgoKHQodCwAF3AAAAAAAAAAAAAAAAAAA'
        command_off: 'sgBKAQsdCh0LHAsdCxwKHh4JCx0KHQoeCh0LHQodCh0eCh4KCh0eCR4KHgkeCh4JCh4LHQodCh0LHQodHgoKHQsdCpELHQodCx0KHQodCx0KHR4KCxwLHQodCh4KHQscCx0eCh0KCxweCh4JHgoeCR4KCh4KHQodCx0KHQsdHgkKHgodCpIKHQodCx0KHQsdCh0LHR0KCx0KHQsdCh0LHAsdCh0eCh0LCh0dCx0KHgkeCh4JCx0KHQsdCh0LHQodHgoKHQscC5ELHQodCx0KHQoeCh0KHR4KCxwKHgodCx0KHQsdCh0eCh0KCh4dCh4KHQoeCh0KCh0LHQscCx0KHQsdHQoKHgodCpIKHQsdCh0LHAsdCh0LHR0KCx0KHQsdCh0LHQodCxweCh4KCh0eCR4KHgkeCh4KCh0KHQsdCh0LHQodHgoKHQscCwAF3AAAAAAAAAAAAAAAAAAA'

      # heather room light
      heather_light:
        friendly_name: "heather Light"
        command_on: 'sgBKAQodCh4KHQodCx0KHQoeCR4KHgkdCx0KHQoeCh0LHB4KHQoKHgodCh0eCh0KHQsKHR0KCh4dCgodHgoKHR4JC5ELHQodCh0KHgodCh4KHQodCx0KHQoeChwLHQodCh4KHR4KHQoKHgodCh0eCh0KHQsKHR0KCh0eCgodHgoKHR0KC5EKHQsdCh0KHQsdCh0KHQoeCh0KHgodCh0LHQodCh0LHR0KHgoKHQodCh4dCh4JHgoKHR4KCh0dCgsdHQoKHh0KCpIKHQoeCh0KHQodCx0KHQoeCh0LHAsdCh0KHQsdCh0KHh0KHQsKHQodCh4dCh0KHgoKHR0KCx0dCgsdHQoLHB4KCpIKHQodCx0KHQodCx0KHQoeCh0KHQscCx0KHQsdCh0KHR4KHQoLHQodCxweCh0KHgoKHR4JCx0dCgodHgoKHR4KCgAF3AAAAAAAAAAAAAAAAAAA'
        command_off: 'sgBKAQodCh0LHAsdCh0LHR0KCx0KHQodCx0KHQoeCh0dCh4JHgoKHgodCh0eCh0KHQoLHR0KCxweCgodHgkLHR0KC5EKHQodCh4KHQoeCh0KHR4KCh0KHQoeCh0KHQsdCh0dCx0KHQoLHQodCh0eCh0KHgoKHR0KCx0dCgoeHQkLHR4JC5EKHQsdCh0KHQsdCh0KHR4KCh0KHgodCh0KHgodCh0eCh0KHQsKHQodCx0dCh0KHgoKHR4KCh0eCQsdHQoKHh0KCpEKHgodCh0KHgodCh0LHB4KCx0KHQodCh0LHQodCxweCh0LHQoKHgodCh0dCh4KHQoKHR4KCh0eCgodHQoLHR0KCpELHQodCh0KHgodCh4KHR0LCR4KHQodCh4KHQodCx0dCh4KHQoKHgodCh0eCR4KHQsJHh0KCh0eCgodHQsKHR0KCgAF3AAAAAAAAAAAAAAAAAAA'

      # baby room light
      baby_light:
        friendly_name: "baby Light"
        command_on: 'sgBKAQoeCh0KHgkeCh0KHgodCh4JHgoeCR4JHgoeCR4KHR4KHQoKHgkeCh0KHgodHQsdCgoeCh0dCxwLCh0KHgodCpIKHQoeCh0KHgkeCh0KHgodCh4KHQodCx0KHQoeCh0KHh0KHQsJHgodCh4KHQoeHQodCwkeCh0dCx0KCh4JHgoeCZIKHgodCh4JHgodCh4JHgoeCR4KHgkeCR4KHgkeCh4JHh0LHAsKHQodCx0KHQsdHQodCwkeCh0eCh0KCh4KHQodC5EKHgodCh4KHQodCx0JHgoeCh0KHgkeCh4JHgodCh4JHh0LHAsJHgoeCR4KHgkeHQscCwodCh4dCh0KCx0KHQoeCZMJHgodCh4JHgoeCR4KHgkeCh4JHgodCh4JHgkfCR4KHR0LHQoKHQsdCR4KHgodHQscCwodCh4dCh0LCR4KHQsdCgAF3AAAAAAAAAAAAAAAAAAA'
        command_off: 'sgBKAQkeCh0KHgkeCh0KHh0KCh4JHgoeCR4KHQoeCh0dCx0KHQoKHgodCh4JHgoeHQodCwkeCh0dCx0KCh4JHgodCpIKHQoeCR4JHgoeCR4KHR0LCh4JHgodCh0KHgodCh4dCh4KHAsKHQoeCh4JHQsdHQsdCgodCh4dCh0LCh0KHgkeCZIKHgkeCh4JHgodCh4JHh0LCh0KHQoeCh0KHgkeCh0dCx0KHgoKHQodCx0KHQodHgodCwodCh4cCx0KCh4KHQodCpIKHQoeCh0KHQoeCh0KHh0KCh4KHQodCx0KHQodCx0dCh4KHQoKHgodCh0LHQodHQoeCgodCh4dCh0LCh0KHQoeCpELHAsdCh0LHQodCxwLHR4KCh0LHAsdCh0KHgodCh0eCh0KHgoKHQoeCh0KHQoeHQoeCgodCh4dCh0KCh4KHQodCwAF3AAAAAAAAAAAAAAAAAAA'

google_assistant:
  project_id: 'home-automation-e56fd'
  api_key: !secret gass_key
  exposed_domains:
    - light
    - switch
    - script
    - media_player
    - sensor

ring:
  username: "kolslorr@gmail.com"
  password: !secret ring_password
  
binary_sensor:
  - platform: ring

asuswrt:
  host: 192.168.101.1
  username: 'kolslorr'
  password: !secret router_password
  sensors:
    - upload
    - download
    - upload_speed
    - download_speed