
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
#  themes: !include themes.yaml
   themes: !include_dir_merge_named themes
  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

webostv:
  host: 192.168.101.140
  name: 'Living Room TV'
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: "A8:23:FE:6D:12:04"
  customize:
    sources:
      - livetv
      - youtube
      - Amazon Prime Video
      - Emby
      - desktop

switch:
  - platform: wake_on_lan
    name: "Gaming PC"
    mac: "D0:50:99:85:12:D8"
    host: "192.168.101.6"

# Master bedroom broadlink switch
  - platform: broadlink
    host: 192.168.101.230
    mac: 'c8:f7:42:83:83:6d'
# Living room broadlink switch
  - platform: broadlink
    #host: 192.168.101.56
    mac: '78:0f:77:63:75:f3'
    #type: rm2_pro_plus
    switches:
      # Living room light
        - name: "Living Light"
          command_on: 'sgBKAQodCx0KHgodCh4LHQoeCh0LHQodCx0KHgodCx0LHR0KHgoLHQoeCh0eCgodHgoeCgsdHQoeCgoeCh0LHQodC5MKHQsdCxwLHQsdCh0LHQoeCh4KHQsdCh0LHQsdCh4KHR4KHgoKHQsdCh4dCgoeHQsdCwodHgodCwodCxwLHQsdCpMKHgodCx0KHQsdCx0KHgodCx0KHgodCx0KHgodCx0KHh4JHgoKHQsdCx0eCQsdHgoeCgodHgoeCgoeCh0LHQoeCpILHQsdCh0LHQoeCh0LHQoeCh0LHQsdCh0LHQodCx0LHR4KHgkLHQsdCh4dCgsdHgodCgsdHgodCgsdCh4KHQsdCpMKHgodCx0KHQsdCh4KHQsdCx0KHQsdCx0KHQsdCh4KHh0KHgoKHgodCx0eCQsdHgoeCgoeHQoeCgodCx0KHgodCwAF3AAAAAAAAAAAAAAAAAAA'
          command_off: 'sgBKAQodCx0LHQoeCh0KHh0LCh0KHgoeCh0LHQodCx0eCh4KHQsKHQsdCh0eCgoeHQsdCgsdHgodCgoeCx0KHQsdCpMKHQoeCh0LHQodCx0LHR4KCh4KHQoeCh0LHQoeCh0eCh4KHQsKHQsdCh4dCgsdHQseCgodHgodCgsdCx0KHgodC5IKHgodCh4KHQsdCh4KHh0KCx0KHgodCx0KHQsdCh4eCh0KHgoKHgodCx0dCwodHgoeCgodHgoeCgodCx0LHQoeCpIKHgodCx0LHAsdCx0KHh4JCx0KHgodCx0LHQoeCh0eCh4KHgkLHQoeCh0eCgodHgoeCgsdHQoeCgoeCh0LHQoeCpMKHgoeCh0LHQodCx0KHh4KCh4KHQoeCh0LHQodCx0eCh4KHgkLHQoeCh0eCgsdHQseCQsdHgodCgoeCh0LHQoeCgAF3AAAAAAAAAAAAAAAAAAA'

      # Living room aircon
        - name: "Living Aircon Cool"
          command_on: 'JgBMAnA6DioOKw8OEQsODw0sDQ8RDA0sDSwODhEoDg8NEBEnDyoODxEnDisPDhELDisODw0PDisNEBEMDQ8RCxEMEQsRDBEMEAwRCxEMEQsODxELDg8RCxILEQwNDw4PDSwODg4PEQsRDBELESgRKA4PEQsODw0sDQ8ODxEoDQ8RDA0QDQ8RDA0rDyoPDg0rDisPDg0QEAwRDA0QEAwODxELESgODxAoDw4OKw0sDisNKw4rDw4RCxEMEQsRDA4PDQ8ODxELEgsODxELDg8RCxEMEQsRDBAMEQwRCxEMEQsODxEMDQ8RDA8ODg4RDBAMDg8RDBELEQwQDBEMEQsODxELEA0NEBAMEQwQDA0QDQ8RDBELEQwNLA0PDg8NLA4ODg8RJw8ODQACMnU6DSwNKw8OEQwNEBAoDg8QDBEoDisODhEoDRAQDBEoDSwODhEoDisNDxEMESgODhEMDSwODxAMDRAQDBAMEQwRCxEMEAwQDRANEAwODxAMDg8QDBANDw4RCxEMDisODxELEQwQDBEMECkQKA8OEQsRDBApDQ8QDQ0sDg4ODxELDg8RCxApDyoODw0rEycQDA4PEQsQDRELEQwQDQ0PESgODg4sDQ8RKA4rDioPKg8qEQsODxANEQsODxELEQwQDA4PEAwQDQ8OEA0QDA4PEAwQDRELEQwRCxEMDRAPDRANDQ8QDRELEA0NDw4PEQsQDRAMDg8QDQ0PEQwODxAMEA0QDBANEAwRDBAMDg8RCw4PEA0NLA0PEQ0MLA4OEQwQKRAMEQANBQAAAAAAAAAAAAAAAA=='
          command_off: 'JgBMAnI4DisNLA4OEA0QDA4rDw4QDA4rDisODw0rDw4QDBApDisQDRApDisQDBANECgPDhANDykPDg0QDw0QDBANEA0NDxANDQ8ODw0QEAwPDg8NEA0NDxANEAwODxAMDw4NEA8NEA0NDxANECkRKA0PEA0QDA8qDw4QDBApDg8PDQ8NDg8ODw0rECkODxApDisODg4PEAwPDg4PDQ8ODw0QDykODxApDQ8QKQ4rECgOKw8qDg4QDQ0QDw0ODw4OEA0QDBANEAwQDQ8NEA0ODg4PEAwODxANDw4ODg8OEAwODw8ODw0QDQ8NEAwQDQ0QDw0QDQ0PEA0PDRANDQ8ODw8ODw0PDQ4PEA0NEA4ODg8QDBANDg4PKhAMEA0PKhAMDisODw8NDgACNnU6DisPKQ8ODw0ODw8qDg4QDRApDioODw0sDQ8ODw4rDisODhApDyoODg4PECkODg4PDyoODhANDQ8QDRAMDg8ODw8NDg8PDRANDw0PDg8NDg8PDg0PDw4PDg0PDg8PDRANEAwPDhAMDyoOKw4ODg8PDg8pDw4PDRApDg8PDQ8ODg4QDBApDisNEBAoDisPDhAMEA0QDBANDw4NDxANDyoODg8qDw0PKg8qDisOKw4rDg4ODw4OEA0PDRAMEA0NEA0PDw4PDQ8ODw0PDg8NEA0PDRANDRAODg4PDw0QDQ8NEA0QDBANDw0PDg8NDg8QDA4PDw4PDQ8ODw4QDA4PDw0QDRANDw0QDA8ODRAPDRANDQ8QKQ8ODQ8OKw8ODSsPDg8NEAANBQAAAAAAAAAAAAAAAA=='

      # Master room light
        - name: "Master Light"
          command_on: 'sgBKAQodCh0LHQodCx0KHQoeCh0KHQsdCh4KHQoeCh0KHR4KCh0eCh4JHgodCh4KCh0KHgodCh4KHQoeHQoKHQsdCpIKHQsdCh0LHQodCx0KHQsdCh0LHQodCx0KHQoeCh0KHR4KCh0eCh4JHgoeCR4KCh0LHQodCx0KHQsdHQoLHAsdCpILHQodCx0KHQoeCh0LHQodCh0LHQodCx0KHQsdCh0KHh0KCh4dCh4KHQoeCh0KCh4KHQsdCh0KHQsdHgkLHQodCpMKHQodCx0LHAsdCh0LHQodCx0KHQsdCh0KHgodCxwLHR4KCh0dCx0KHQsdCh0KCx0KHQsdCxwKHgodHgoKHQodC5IKHQodCx0LHAsdCh0LHQoeCh0KHQscCx0KHgodCh0LHR4JCx0dCh4KHgkeCh4JCx0KHQsdCh0LHQodHgoKHQodCwAF3AAAAAAAAAAAAAAAAAAA'
          command_off: 'sgBKAQsdCh0LHAsdCxwKHh4JCx0KHQoeCh0LHQodCh0eCh4KCh0eCR4KHgkeCh4JCh4LHQodCh0LHQodHgoKHQsdCpELHQodCx0KHQodCx0KHR4KCxwLHQodCh4KHQscCx0eCh0KCxweCh4JHgoeCR4KCh4KHQodCx0KHQsdHgkKHgodCpIKHQodCx0KHQsdCh0LHR0KCx0KHQsdCh0LHAsdCh0eCh0LCh0dCx0KHgkeCh4JCx0KHQsdCh0LHQodHgoKHQscC5ELHQodCx0KHQoeCh0KHR4KCxwKHgodCx0KHQsdCh0eCh0KCh4dCh4KHQoeCh0KCh0LHQscCx0KHQsdHQoKHgodCpIKHQsdCh0LHAsdCh0LHR0KCx0KHQsdCh0LHQodCxweCh4KCh0eCR4KHgkeCh4KCh0KHQsdCh0LHQodHgoKHQscCwAF3AAAAAAAAAAAAAAAAAAA'

      # heather room light
        - name: "heather Light"
          command_on: 'sgBKAQodCh4KHQodCx0KHQoeCR4KHgkdCx0KHQoeCh0LHB4KHQoKHgodCh0eCh0KHQsKHR0KCh4dCgodHgoKHR4JC5ELHQodCh0KHgodCh4KHQodCx0KHQoeChwLHQodCh4KHR4KHQoKHgodCh0eCh0KHQsKHR0KCh0eCgodHgoKHR0KC5EKHQsdCh0KHQsdCh0KHQoeCh0KHgodCh0LHQodCh0LHR0KHgoKHQodCh4dCh4JHgoKHR4KCh0dCgsdHQoKHh0KCpIKHQoeCh0KHQodCx0KHQoeCh0LHAsdCh0KHQsdCh0KHh0KHQsKHQodCh4dCh0KHgoKHR0KCx0dCgsdHQoLHB4KCpIKHQodCx0KHQodCx0KHQoeCh0KHQscCx0KHQsdCh0KHR4KHQoLHQodCxweCh0KHgoKHR4JCx0dCgodHgoKHR4KCgAF3AAAAAAAAAAAAAAAAAAA'
          command_off: 'sgBKAQodCh0LHAsdCh0LHR0KCx0KHQodCx0KHQoeCh0dCh4JHgoKHgodCh0eCh0KHQoLHR0KCxweCgodHgkLHR0KC5EKHQodCh4KHQoeCh0KHR4KCh0KHQoeCh0KHQsdCh0dCx0KHQoLHQodCh0eCh0KHgoKHR0KCx0dCgoeHQkLHR4JC5EKHQsdCh0KHQsdCh0KHR4KCh0KHgodCh0KHgodCh0eCh0KHQsKHQodCx0dCh0KHgoKHR4KCh0eCQsdHQoKHh0KCpEKHgodCh0KHgodCh0LHB4KCx0KHQodCh0LHQodCxweCh0LHQoKHgodCh0dCh4KHQoKHR4KCh0eCgodHQoLHR0KCpELHQodCh0KHgodCh4KHR0LCR4KHQodCh4KHQodCx0dCh4KHQoKHgodCh0eCR4KHQsJHh0KCh0eCgodHQsKHR0KCgAF3AAAAAAAAAAAAAAAAAAA'

      # study room light
        - name: "study Light"
          command_on: 'sgBKAQoeCh0KHgkeCh0KHgodCh4JHgoeCR4JHgoeCR4KHR4KHQoKHgkeCh0KHgodHQsdCgoeCh0dCxwLCh0KHgodCpIKHQoeCh0KHgkeCh0KHgodCh4KHQodCx0KHQoeCh0KHh0KHQsJHgodCh4KHQoeHQodCwkeCh0dCx0KCh4JHgoeCZIKHgodCh4JHgodCh4JHgoeCR4KHgkeCR4KHgkeCh4JHh0LHAsKHQodCx0KHQsdHQodCwkeCh0eCh0KCh4KHQodC5EKHgodCh4KHQodCx0JHgoeCh0KHgkeCh4JHgodCh4JHh0LHAsJHgoeCR4KHgkeHQscCwodCh4dCh0KCx0KHQoeCZMJHgodCh4JHgoeCR4KHgkeCh4JHgodCh4JHgkfCR4KHR0LHQoKHQsdCR4KHgodHQscCwodCh4dCh0LCR4KHQsdCgAF3AAAAAAAAAAAAAAAAAAA'
          command_off: 'sgBKAQkeCh0KHgkeCh0KHh0KCh4JHgoeCR4KHQoeCh0dCx0KHQoKHgodCh4JHgoeHQodCwkeCh0dCx0KCh4JHgodCpIKHQoeCR4JHgoeCR4KHR0LCh4JHgodCh0KHgodCh4dCh4KHAsKHQoeCh4JHQsdHQsdCgodCh4dCh0LCh0KHgkeCZIKHgkeCh4JHgodCh4JHh0LCh0KHQoeCh0KHgkeCh0dCx0KHgoKHQodCx0KHQodHgodCwodCh4cCx0KCh4KHQodCpIKHQoeCh0KHQoeCh0KHh0KCh4KHQodCx0KHQodCx0dCh4KHQoKHgodCh0LHQodHQoeCgodCh4dCh0LCh0KHQoeCpELHAsdCh0LHQodCxwLHR4KCh0LHAsdCh0KHgodCh0eCh0KHgoKHQoeCh0KHQoeHQoeCgodCh4dCh0KCh4KHQodCwAF3AAAAAAAAAAAAAAAAAAA'

      # TV Console LED
        - name: "TV Console LED"
          command_on: 'JgBYAAABKpUUERMTEhMUERQSEhMTEhMTEjcTOBI3EzcTEhM3FDYTNxMSEzcTEhQSExITEhQSEhMUNhMSEzcTNxI3EzcTNxQ2EwAFRQABKUsSAAxdAAErSRMADQU='
          command_off: 'JgBgAAABKpUUERQSEhMUERQSExITEhMTEzYUNhQ2EzcTEhQ2EzcTNxI3EzcUEhITExITExITExITExITFDYTNxI3EzcTNxQ2EwAFRQABKkoSAAxdAAErSRMADF0AASlKFAANBQAAAAAAAAAA'

vacuum:
  - platform: deebot
    username: kolslorr@gmail.com
    password: Have6funs
    country: sg
    continent: ww
    deviceid: E02R12796B09HCAD0381
    live_map: True                    # Enable Live Map.. may cause issues on low power hardware | Default: True
    show_color_rooms: True           # Enable draw room colors as in the app | Default: False
    livemappath: 'www/live_map.png'

camera:
  - platform: generic
    name: Deebot_live_map
    still_image_url: "http://192.168.101.5:8123/local/live_map.png" #Example configuration for livemappath: 'www/live_map.png'
    verify_ssl: false
    
google_assistant:
  project_id: 'home-automation-e56fd'
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  exposed_domains:
    - light
    - switch
    - script
    - media_player
    - sensor
    - vacuum

binary_sensor:
  - platform: workday
    country: "SG"
 
asuswrt:
  host: 192.168.101.1
  username: 'kolslorr'
  password: !secret router_password
  sensors:
    - upload
    - download
    - upload_speed
    - download_speed

device_tracker:
  - platform: ping
    hosts:
      oneplus7t: 192.168.101.51
      mi9se: 192.168.101.246